### ISSUE TITLE
Observable calls nullpointer

### ISSUE THREAD

**Issue by andretortolano** [andretortolano/GithubSearch#6]
When changing fragments or onConfigurationChange between observable calls, NullPointerException shows for views that are no longer attached to UI

**Comment by andretortolano** [comment]
Caused by: rx.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'void android.widget.ProgressBar.setVisibility(int)' on a null object reference
                                                                                             at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
                                                                                             at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
                                                                                             at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
                                                                                             at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
                                                                                             at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
                                                                                             at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:204)
                                                                                             at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144)
                                                                                             at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:227)
                                                                                             at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
                                                                                             at android.os.Handler.handleCallback(Handler.java:815) 
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                                             at android.os.Looper.loop(Looper.java:194) 
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:5631) 
                                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959) 
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754) ``

**Comment by andretortolano** [comment]
Done in refactory_01
